### PR TITLE
License detector and feeder

### PR DESCRIPTION
**Pull request by michelescarlato**
## Description
This branch contains the license feeder, that will consume a kafka topic generated by the license detector (License detector Java and Python). 

## Motivation and context
This integrates the license detection at the package and at the file level for two languages (still minor improvements for Python are required).

## Testing
We tested the license-detector and the feeder within the Java pipeline (on Monster, and on docker-compose).

## Task list  
- [x] Fix the import from #301 (we were using an old version of fasten) of the license-detector and the license-feeder.

### CODE REVIEW

**Comment by MagielBruntink** [comment]
The build on the windows-2019 environment fails because of a test failure:
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.98 s <<< FAILURE! - in eu.fasten.analyzer.licensefeeder.LicenseFeederIntegrationTest
Error:  eu.fasten.analyzer.licensefeeder.LicenseFeederIntegrationTest  Time elapsed: 1.98 s  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at eu.fasten.analyzer.licensefeeder.LicenseFeederIntegrationTest.startPostgresInstance(LicenseFeederIntegrationTest.java:28)
```
Apparently, a Docker host is needed to run these tests. The windows-2019 environment has Docker installed, so it's unclear to me why the test is failing.

**Comment by MagielBruntink** [comment]
On my local Windows 11 machine with Docker running, the test for license feedder succeeds.

**Comment by MagielBruntink** [comment]
@michelescarlato 
Could you please try two things:
 - in `pom.xml` update the org.testcontainers:postgresql to 1.16.3
 - in `fasten/.github/workflows/maven_develop.yml` change windows-2019 to windows-2022?

**Comment by MagielBruntink** [comment]
@michelescarlato Sorry for the mess I made here. I brought your Github Actions in line with the changes on the main develop branch so they should work now in case of a merge. I upgrade the testcontainers and the windows runner, let's see if that resolves the problem with test failure.

**Comment by MagielBruntink** [comment]
Ok, all builds succeed, I'll leave it at this.

**Comment by michelescarlato** [comment]
> @michelescarlato Could you please try two things:
> 
> * in `fasten/analyzer/license-feeder/pom.xml` update the org.testcontainers:postgresql to 1.16.3
> * in `fasten/.github/workflows/maven_develop.yml` change windows-2019 to windows-2022?

Hi @MagielBruntink, I saw your tentatives went through correctly (namely, now the build it is completing, through disabling the integration test if Docker is not available).

Can I consider it good enough for now? 
Or do we still need to study a better solution?

Meanwhile, I will test the correct functioning of the feeder.

Thanks a lot for your efforts and your help! Without it, I was lost.

**Comment by MagielBruntink** [comment]
> Hi @MagielBruntink, I saw your tentatives went through correctly (namely, now the build it is completing, through disabling the integration test if Docker is not available).
> 
> Can I consider it good enough for now? Or do we still need to study a better solution?

Best we can do now. The fix is that those windows GitHub runners get better Docker support, but that’s out of our hands.

**Comment by MagielBruntink** [comment]
@michelescarlato did you mean to close this PR without merging it?

**Comment by michelescarlato** [comment]
All tests are now fine, shall we merge this pr, please?
@mir-am @proksch

**Comment by mir-am** [comment]
> All tests are now OK. Shall we merge this pr, please? @mir-am @proksch
> 
> We decided to merge the Debian license detector (we will create a new PR for that) only after merging the license detector and license feeder.
> 
> It means that for this PR, no tasks are left.
> 
> The reason is: that I am still working on the feeding part in Debian, and we would really need to have these two components merged as soon as possible.

There is still a conflict with `develop`. Could you please resolve the remaining conflicts?
Then, we will merge this PR.

**Comment by michelescarlato** [comment]
> > All tests are now OK. Shall we merge this pr, please? @mir-am @proksch
> > We decided to merge the Debian license detector (we will create a new PR for that) only after merging the license detector and license feeder.
> > It means that for this PR, no tasks are left.
> > The reason is: that I am still working on the feeding part in Debian, and we would really need to have these two components merged as soon as possible.
> 
> There is still a conflict with `develop`. Could you please resolve the remaining conflicts? Then, we will merge this PR.

Sorry @mir-am Amir, where can I see the conflicts?

**Comment by MagielBruntink** [comment]
There are no conflicts between the tip of this branch and develop. However, at some point there were conflicts, which causes that Github does not want to do an automatic rebase-and-merge. If you select simple "Merge pull request" you see you can merge it now without conflict. I would argue for simply merging without rebase.

**Comment by michelescarlato** [comment]
> I would argue for simply merging without rebase

I am trying to rebase with:

```
michelescarlato@bebop:~/fasten$ git rebase develop license-detector-and-feeder 
First, rewinding head to replay your work on top of it...
Applying: creating debian license collector branch
Applying: Update pom.xml
Applying: Update pom.xml
Applying: Update DebianLicenseDetectorPlugin.java
Applying: renaming directory
Applying: Commenting part of the code that currently wouldn't compile (license feeder is missing on this branch).
Applying: commenting the setTopics
Applying: Handling exceptions following fasten guidelines in the consume method.
Applying: fixing the methods extractPackageName and extractPackageVersion
Applying: fixing the JSON key
Applying: updating extractPackageName and extractPackageVersion after testing them on the DebianAPIJavaLib
Applying: fixing a ;
Applying: fixed the package name
Applying: removing temporarily the DetectedLicenses classes
Applying: added Michele's information
Applying: changed the artifact id
Applying: updated extractPackageName and extractPackageVersion functions.
Applying: Create docker-compose.yml
Applying: adding files that are present in the #301 pull request
Applying: adding files that are present in the pull request #301
Applying: Retrieving package name from source instead of package
Applying: importing files from the endocode/compliancePlugin branch
Applying: merging modifications from endocode/licenseCompliance branch
Using index info to reconstruct a base tree...
M	core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Falling back to patching base and 3-way merge...
Auto-merging core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
CONFLICT (content): Merge conflict in core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
error: Failed to merge in the changes.
Patch failed at 0023 merging modifications from endocode/licenseCompliance branch
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

Following  `hint: Use 'git am --show-current-patch' to see the failed patch`, I got this output:


```
michelescarlato@bebop:~/fasten$ git am --show-current-patch
commit bb81fd9298cd793c842e1a29bbe0f61afa49da7c
Author: Michele Scarlato <michele.scarlato@gmail.com>
Date:   Wed Feb 23 16:05:52 2022 +0100

    merging modifications from endocode/licenseCompliance branch

diff --git a/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java b/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
index 4c286b53..7ac5399d 100644
--- a/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
+++ b/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
@@ -57,6 +57,8 @@ import com.google.gson.GsonBuilder;
 
 import eu.fasten.core.data.Constants;
 import eu.fasten.core.data.FastenJavaURI;
+import eu.fasten.core.maven.data.Revision;
+import eu.fasten.core.maven.utils.MavenUtilities;
 import eu.fasten.core.data.metadatadb.codegen.Keys;
 import eu.fasten.core.data.metadatadb.codegen.enums.Access;
 import eu.fasten.core.data.metadatadb.codegen.enums.CallableType;
@@ -84,6 +86,9 @@ import eu.fasten.core.data.metadatadb.codegen.tables.records.CallablesRecord;
 import eu.fasten.core.maven.data.PackageVersionNotFoundException;
:...skipping...
commit bb81fd9298cd793c842e1a29bbe0f61afa49da7c
Author: Michele Scarlato <michele.scarlato@gmail.com>
Date:   Wed Feb 23 16:05:52 2022 +0100

    merging modifications from endocode/licenseCompliance branch

diff --git a/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java b/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
index 4c286b53..7ac5399d 100644
--- a/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
+++ b/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
@@ -57,6 +57,8 @@ import com.google.gson.GsonBuilder;
 
 import eu.fasten.core.data.Constants;
 import eu.fasten.core.data.FastenJavaURI;
+import eu.fasten.core.maven.data.Revision;
+import eu.fasten.core.maven.utils.MavenUtilities;
 import eu.fasten.core.data.metadatadb.codegen.Keys;
 import eu.fasten.core.data.metadatadb.codegen.enums.Access;
 import eu.fasten.core.data.metadatadb.codegen.enums.CallableType;
@@ -84,6 +86,9 @@ import eu.fasten.core.data.metadatadb.codegen.tables.records.CallablesRecord;
 import eu.fasten.core.maven.data.PackageVersionNotFoundException;
 import eu.fasten.core.utils.FastenUriUtils;
 
+import javax.annotation.Nullable;
+
+
 public class MetadataDao {
     private final Logger logger = LoggerFactory.getLogger(MetadataDao.class.getName());
     private DSLContext context;
@@ -215,6 +220,164 @@ public class MetadataDao {
         return resultRecord.getValue(PackageVersions.PACKAGE_VERSIONS.ID);
     }
 
+    /**
+     * Inserts outbound licenses at the package version level.
+     *
+     * @param coordinates the coordinates whose outbound licenses are about to be inserted.
+     * @param outboundLicenses the package version's outbound licenses.
+     * @return the updated metadata field.
+     */
+    public String insertPackageOutboundLicenses(Revision coordinates,
+                                                String outboundLicenses) {
+        return insertPackageOutboundLicenses(
+                coordinates.groupId,
+                coordinates.artifactId,
+                coordinates.version.toString(),
+                outboundLicenses);
+    }
+
+    /**
+     * Inserts outbound licenses at the package version level.
+     *
+     * @param groupId          the group ID of the package version whose outbound licenses are about to be inserted.
+     * @param artifactId       the artifact ID of the package version whose outbound licenses are about to be inserted.
+     * @param packageVersion   the package version whose outbound licenses are about to be inserted.
+     * @param outboundLicenses the package version's outbound licenses.
+     * @return the updated metadata field.
+     */
+    public String insertPackageOutboundLicenses(String groupId,
+                                                String artifactId,
+                                                String packageVersion,
+                                                String outboundLicenses) {
+        return insertPackageOutboundLicenses(
+                MavenUtilities.getMavenCoordinateName(groupId, artifactId),
+                packageVersion,
+                outboundLicenses);
+    }
+    /**
+     * Inserts outbound licenses at the package version level.
+     *
+     * @param packageName      the package name whose outbound licenses are about to be inserted.
+     * @param packageVersion   the package version whose outbound licenses are about to be inserted.
+     * @param outboundLicenses the package version's outbound licenses.
+     * @return the updated metadata field.
+     */
+    public String insertPackageOutboundLicenses(String packageName, String packageVersion, String outboundLicenses) {
+
+        logger.debug("Inserting outbound licenses for " + packageName + ":" + packageVersion + ": " + outboundLicenses);
+
+        /*  Warning!
+            The `concat()` method casts the first argument to `VARCHAR`, causing errors!
+            Packages p = Packages.PACKAGES;
+            PackageVersions pv = PackageVersions.PACKAGE_VERSIONS;
+            Record updatedMetadata = context.update(pv)
+                    .set(
+                            pv.METADATA,
+                            when(pv.METADATA.isNull(), JSONB.valueOf("{}")).otherwise(pv.METADATA)
+                                    .concat(outboundLicenses).cast(SQLDataType.JSONB)
+                    )
+                    .from(p)
+                    .where(p.ID.eq(pv.PACKAGE_ID).and(packageVersionWhereClause(packageName, packageVersion)))
+                    .returning(pv.METADATA)
+                    .fetchOne();
+        */
+        // Using plain SQL
+        Object updatedMetadata = context.fetchValue("UPDATE package_versions pv\n" +
+                "SET metadata = (CASE WHEN metadata IS NULL THEN '{}'::jsonb ELSE metadata END) || {0}\n" +
+                "    FROM packages p\n" +
+                "WHERE p.id = pv.package_id\n" +
+                "  AND p.package_name = LOWER({1})\n" +
+                "  AND pv.version = LOWER({2})\n" +
+                "    RETURNING pv.metadata;", JSONB.valueOf(outboundLicenses), packageName, packageVersion);
+
+        // Updated metadata field
+        logger.debug("`updatedMetadata`: " + updatedMetadata);
+        assert updatedMetadata != null; // FIXME
+        return updatedMetadata.toString();
+    }
+    /**
+     * Inserts scanned licenses at the file level.
+     *
+     * @param coordinates  the Maven coordinates to which the file belongs.
+     * @param filePath     the path of the file whose scanned licenses are about to be inserte.
+     * @param fileLicenses the scanned licenses of the file.
+     * @return the updated metadata field. Can be `null` in case the file is not present in the DB.
+     */
+    @Nullable
+    public String insertFileLicenses(Revision coordinates,
+                                     String filePath,
+                                     String fileLicenses) {
+        return insertFileLicenses(
+                coordinates.groupId,
+                coordinates.artifactId,
+                coordinates.version.toString(),
+                filePath,
+                fileLicenses);
+    }
+
+    /**
+     * Inserts scanned licenses at the file level.
+     *
+     * @param groupId        the group ID of the package to which the file belongs.
+     * @param artifactId     the artifact ID of the package to which the file belongs.
+     * @param packageVersion the version of the package to which the file belongs.
+     * @param filePath       the path of the file whose scanned licenses are about to be inserte.
+     * @param fileLicenses   the scanned licenses of the file.
+     * @return the updated metadata field. Can be `null` in case the file is not present in the DB.
+     */
+    @Nullable
+    public String insertFileLicenses(String groupId,
+                                     String artifactId,
+                                     String packageVersion,
+                                     String filePath,
+                                     String fileLicenses) {
+        return insertFileLicenses(
+                MavenUtilities.getMavenCoordinateName(groupId, artifactId),
+                packageVersion,
+                filePath,
+                fileLicenses);
+    }
+
+    /**
+     * Inserts scanned licenses at the file level.
+     *
+     * @param packageName    the name of the package to which the file belongs.
+     * @param packageVersion the version of the package to which the file belongs.
+     * @param filePath       the path of the file whose scanned licenses are about to be inserte.
+     * @param fileLicenses   the scanned licenses of the file.
+     * @return the updated metadata field. Can be `null` in case the file is not present in the DB.
+     */
+    @Nullable
+    public String insertFileLicenses(String packageName,
+                                     String packageVersion,
+                                     String filePath,
+                                     String fileLicenses) {
+
+        logger.debug("Inserting file licenses for " + packageName + ":" + packageVersion + ", file" +
+                filePath + ": " + fileLicenses);
+
+        // Can be `null` in case the DB does not have this file
+        @Nullable Object updatedMetadata = context.fetchValue("UPDATE files f\n" +
+                        "SET metadata = (CASE WHEN f.metadata IS NULL THEN '{}'::jsonb ELSE f.metadata END) || {0}\n" +
+                        "    FROM packages p JOIN package_versions pv ON p.id = pv.package_id\n" +
+                        "WHERE f.package_version_id = pv.id\n" +
+                        "  AND p.package_name = LOWER({1})\n" +
+                        "  AND pv.version = LOWER({2})\n" +
+                        "  AND f.path ILIKE '%' || array_to_string(" +
+                        "    (regexp_split_to_array({3}, '/'))[(array_length(regexp_split_to_array({3}, '/'), 1) - 1):],\n" +
+                        "    '/')\n" +
+                        "    RETURNING f.metadata;\n",
+                JSONB.valueOf(fileLicenses),
+                packageName,
+                packageVersion,
+                filePath);
+
+        logger.debug("`updatedMetadata`: " + updatedMetadata);
+
+        // Updated metadata field
+        return updatedMetadata == null ? null : updatedMetadata.toString();
+    }
+
     /**
      * Inserts a record in the 'dependencies' table in the database.
      *
diff --git a/core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java b/core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java
index c71d24cf..bec89db6 100644
--- a/core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java
+++ b/core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java
@@ -29,6 +29,7 @@ import org.apache.commons.io.FileUtils;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+import javax.annotation.Nullable;
 import java.io.BufferedReader;
 import java.io.File;
 import java.io.FileReader;
@@ -231,4 +232,29 @@ public class MavenUtilities {
         }
     }
 
+    /**
+     * Pretty-prints Maven coordinates.
+     *
+     * @param groupId    the maven coordinate's group ID.
+     * @param artifactId the maven coordinate's artifact ID.
+     * @return a pretty String representation of the input Maven coordinate.
+     */
+    public static String getMavenCoordinateName(String groupId, @Nullable String artifactId) {
+        return groupId +
+                (artifactId == null || artifactId.compareTo("") == 0 ?
+                        "" : Constants.mvnCoordinateSeparator + artifactId);
+    }
+
+    /**
+     * Pretty-prints Maven coordinates (with version).
+     *
+     * @param groupId    the maven coordinate's group ID.
+     * @param artifactId the maven coordinate's artifact ID.
+     * @param version    the maven coordinate's version.
+     * @return a pretty String representation of the input Maven coordinate.
+     */
+    public static String getMavenCoordinateName(String groupId, String artifactId, String version) {
+        return getMavenCoordinateName(groupId, artifactId) + Constants.mvnCoordinateSeparator + version;
+    }
+
 }

```

**Comment by MagielBruntink** [comment]
Yes, that's why Github doesn't want to do it. It cannot replay the changes on top of develop/HEAD without running into conflicts. You can do it locally by resolving the conflict, or you could merge without rebase (which will lead to a merge commit, but I suppose that we could live with that for this time).

**Comment by michelescarlato** [comment]
> Yes, that's why Github doesn't want to do it. It cannot replay the changes on top of develop/HEAD without running into conflicts. You can do it locally by resolving the conflict, or you could merge without rebase (which will lead to a merge commit, but I suppose that we could live with that for this time).

I am sorry but I am not understanding how to resolve the conflict locally. 
What do you suggest doing?

**Pull request merged**
