### PR TITLE
Removed vulnerability-consumer

### PR DESCRIPTION
**Pull request by MagielBruntink**
## Description
Removed the vulnerability-consumer code from analyzer.

## Motivation and context
With the vulnerability-statements-processor and the vulnerability-packages-listener, the old (and buggy) vulnerability-consumer is redundant.

## Testing
All tests succeed.

### CODE REVIEW

**Review by mir-am — APPROVED** [review]
We should remove the previous vuln. consumer. However, before doing so, I'd like to deploy the new solution first on `monster` to ensure that it runs as expected.

**Comment by MagielBruntink** [comment]
Hi @mir-am

Thanks. The deployment configuration is quite similar to the vulnerability-consumer, I think it's almost a drop in replacement.

One important thing is that the metadata DB needs to be updated with the new tables. Was that already done before?

The statements processor replaces the vulnrability-consumer service:
https://github.com/fasten-project/fasten-docker-deployment/blob/3ef629b2058e8acf62fcf6b067c0439a1bb52948/docker-compose.yml#L244

Then the packages listener is a new service that updates package-versions with existing vulnerability data as they come in.
https://github.com/fasten-project/fasten-docker-deployment/blob/3ef629b2058e8acf62fcf6b067c0439a1bb52948/docker-compose.yml#L273

**Comment by mir-am** [comment]
> Hi @mir-am
> 
> Thanks. The deployment configuration is quite similar to the vulnerability-consumer, I think it's almost a drop in replacement.
> 
> One important thing is that the metadata DB needs to be updated with the new tables. Was that already done before?
> 
> The statements processor replaces the vulnrability-consumer service: https://github.com/fasten-project/fasten-docker-deployment/blob/3ef629b2058e8acf62fcf6b067c0439a1bb52948/docker-compose.yml#L244
> 
> Then the packages listener is a new service that updates package-versions with existing vulnerability data as they come in. https://github.com/fasten-project/fasten-docker-deployment/blob/3ef629b2058e8acf62fcf6b067c0439a1bb52948/docker-compose.yml#L273

For the new deployment of the FASTEN pipeline, I have already added the manifest files for the two plug-ins and the creation of the DB tables. That said, we have not started the new deployment yet as there are some remaining tasks to be done.
https://github.com/fasten-project/k8s-deployments/tree/xmas-deploy/fasten/vulnerability-analyzer

**Comment by MagielBruntink** [comment]
Are there any tasks that I could help with?

**Comment by mir-am** [comment]
> Are there any tasks that I could help with?

Not for now! I'll let you know if any.

**Comment by proksch** [comment]
I would like to make sure that this is resolved before we restart the pipeline...

Are there any TODOs left? Is the creation of the new tables automatically performed on re-deploy or do we still need to adopt our creation scripts?

**Comment by proksch** [comment]
@mir-am If everything is done, please rebase/merge to close this PR.

**Comment by mir-am** [comment]
> I would like to make sure that this is resolved before we restart the pipeline...
> 
> Are there any TODOs left? Is the creation of the new tables automatically performed on re-deploy or do we still need to adopt our creation scripts?

@proksch 
I have adapted the SQL scripts to create the required tables based on the scripts for the Docker compose.

**Pull request merged**
