### PR TITLE
Added `.dockerignore` file

### PR DESCRIPTION
**Pull request by marcomicera**
## How was it generated

```shell script
# Adding new files manually
cat <<EOT >> .dockerignore
**/.bettercodehub.yml
**/checkstyle.xml
**/LICENSE
**/.gitignore
**/*.md

EOT

# This `.dockerignore` is a superset of `.gitignore`.
# Here I'm prepending `**/` to all the rows that do NOT begin with:
# - `#` (comments)
# - `/` (absolute paths, there used to be some in older commits)
# - `!` (inclusions)
# - `\n` (new lines, i.e., empty rows)
perl -p -e 's-^(?![#/!\n])-**/-g' .gitignore >> .dockerignore
```

## Why

Container optimization.

## To-do's

- Test this on all images
  - [x] [`license-detector`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-detector)
  - [x] [`license-feeder`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder)
  - [ ] Others

### CODE REVIEW

**Comment by marcomicera** [comment]
Converting it into a draft PR, still needs to be tested on all images (I've tested this only with the [`license-detector`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-detector) and the [`license-feeder`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder]).

**Comment by amottier** [comment]
@marcomicera do you think you will get a chance to do the required testing or should we close this PR?

**Comment by marcomicera** [comment]
> @marcomicera do you think you will get a chance to do the required testing or should we close this PR?

Forwarding to @amphioxis

**Comment by proksch** [comment]
Silly question... could we generate this file on the fly in the build? If not, it would be a great idea to include a big note in the beginning of both files to not forget about the other one.

A related question is about the locations of the `.gitignore` files. They can be placed anywhere in the repo, I know that some of our sub-projects have more "local" `.gitignore`s to exclude some build artifacts... I would assume that these are not considered in the `.dockerignore` file, are they?

Apart from that, the PR draft is from July, can we make sure that this is still up to date?

**Comment by proksch** [comment]
There has been no interaction on this PR since two months, so I am closing it for now. Feel free to re-open if needed.

**Pull request closed without merging**
