### PR TITLE
Java license detector & feeder

### PR DESCRIPTION
**Pull request by marcomicera**
# What's in this PR

- The [`license-detector` plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-detector) that:
    1. detects licenses at the package and file level, and
    1. share these findings using the [`fasten.LicenseDetector.out` topic](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenlicensedetector).
- The [`license-feeder` plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder) that:
    1. consumes [`fasten.LicenseDetector.out`](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenlicensedetector) records, and
    1. inserts licenses in the Metadata Database, in the [`package_versions.metadata` and `files.metadata` fields](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema).

# [`license-detector`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-detector) progress

### Steps

- [x] Check whether the repository has already been scanned by querying the KB
    - [`fasten-flink-javasync-taskmanager`](https://github.com/fasten-project/fasten-docker-deployment/blob/c60d6de89797d88c8908bc5e3a0a7b49c0acba74/docker-compose.yml#L447-L460) blocks duplicates:
        ```
        fasten-flink-javasync-taskmanager_1    | INFO  SynchronizeTopics [] - [INCOMING] [org.opentest4j:opentest4j:1.2.0] [fasten.RepoCloner.out] [1627981118041i] [-1] [NONE]
        fasten-flink-javasync-taskmanager_1    | INFO  SynchronizeTopics [] - [DUPLICATE] [org.opentest4j:opentest4j:1.2.0] [fasten.RepoCloner.out] [1627981118041i] [-1] [JoinAlreadyDoneException]
        fasten-flink-javasync-taskmanager_1    | INFO  SynchronizeTopics [] - [INCOMING] [org.opentest4j:opentest4j:1.2.0] [fasten.MetadataDBJavaExtension.out] [1627981118758i] [-1] [NONE]
        fasten-flink-javasync-taskmanager_1    | INFO  SynchronizeTopics [] - [DUPLICATE] [org.opentest4j:opentest4j:1.2.0] [fasten.MetadataDBJavaExtension.out] [1627981118758i] [-1] [JoinAlreadyDoneException]
        ```
        Note how it doesn't `JOIN` these two records.
- [x] Retrieve the outbound license(s)
    - [x] From the `pom.xml` file
    - [x] (_Fallback: using the GitHub API_)
    - ~(_Fallback: from Maven central, if it's possible_)~
- [x] Detect inbound licenses by scanning the project
    - [x] Include `scancode` in the image
    - [x] Start the detection

### Documentation

- [x] [`README.md` file](https://github.com/fasten-project/fasten/blob/endocode/compliancePlugin/analyzer/license-detector/README.md)
- [ ] [Wiki page](https://github.com/fasten-project/fasten/wiki/License-detection)
- [x] [Output Kafka topic](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenlicensedetector)

### Deployment

- [x] [Docker-compose](https://github.com/fasten-project/fasten-docker-deployment/blob/c60d6de89797d88c8908bc5e3a0a7b49c0acba74/docker-compose.yml#L182-L198) (https://github.com/fasten-project/fasten-docker-deployment/pull/8)
    - [x] [`fasten.mvn.releases` test input records](https://github.com/fasten-project/fasten-docker-deployment/tree/license-detector/test-resources/license-detection#feeding-the-whole-pipeline)
    - [x] [`fasten.SyncJava.out` test input records](https://github.com/fasten-project/fasten-docker-deployment/tree/license-detector/test-resources/license-detection#feeding-the-license-detector)
- [ ] [Kubernetes](https://github.com/fasten-project/k8s-deployments/tree/license-detector/fasten/license-detector) (https://github.com/fasten-project/k8s-deployments/pull/15)

# [`license-feeder`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder) progress

### Steps

- [x] Store licenses into the KB
  - [x] Outbound licenses
  - [x] License text found in files

### Documentation

- [x] [`README.md` file](https://github.com/fasten-project/fasten/blob/endocode/compliancePlugin/analyzer/license-feeder/README.md)
- [ ] [Wiki page](https://github.com/fasten-project/fasten/wiki/License-detection)
- [ ] Output Kafka topic

### Deployment

- [x] [Docker-compose](https://github.com/fasten-project/fasten-docker-deployment/blob/c60d6de89797d88c8908bc5e3a0a7b49c0acba74/docker-compose.yml#L200-L219) (https://github.com/fasten-project/fasten-docker-deployment/pull/8)
    - [x] [`fasten.mvn.releases` test input records](https://github.com/fasten-project/fasten-docker-deployment/tree/license-detector/test-resources/license-detection#feeding-the-whole-pipeline)
    - [x] [`fasten.LicenseDetector.out` test input records](https://github.com/fasten-project/fasten-docker-deployment/tree/license-detector/test-resources/license-detection#feeding-the-license-feeder)
- [x] Kubernetes (https://github.com/fasten-project/k8s-deployments/pull/15)

### CODE REVIEW

**Comment by amottier** [comment]
@marcomicera or maybe @amphioxis I was wondering if this PR is now reading for merging?
I'm asking because this plugin is deployed by `fasten-docker-deployment` repository `develop` branch but is (obviously) not currently part of `fasten` repository `develop`.
An alternative would be to isolate deployment of license detector and feeder in a separated branch in `fasten-docker-deployment` repository.

**Comment by marcomicera** [comment]
> @marcomicera or maybe @amphioxis I was wondering if this PR is now reading for merging?

@amphioxis should have taken over this PR, I'm not working on this anymore.
Back then I tested both plugins manually on a dev cluster and they always worked, but extended testing needs to be done by @amphioxis before it gets deployed on the main cluster, as far as I know. Am I right?

> I'm asking because this plugin is deployed by `fasten-docker-deployment` repository `develop` branch but is (obviously) not currently part of `fasten` repository `develop`. An alternative would be to isolate deployment of license detector and feeder in a separated branch in `fasten-docker-deployment` repository.

AFAIK the docker-compose repo is only for local testing, that might be the reason why that PR got merged without proper testing...

**Comment by amottier** [comment]
@amphioxis do you have any news related to the testing related to this PR?

**Comment by amphioxis** [comment]
> @amphioxis do you have any news related to the testing related to this PR?

That is still in progress and hopefully done by next week Wednesday. Told the same to Amir last week, but I had trouble with kafka. Sry for the delay!

**Comment by proksch** [comment]
What is the state of this PR? Please resolve the conflicts with the current `develop` branch to show that this is still actively being worked on, otherwise, I will close the PR soon due to inactivity...

**Comment by michelescarlato** [comment]
@proksch This PR needs to be merged since the license feeder is also used by the Debian license detector (https://github.com/fasten-project/fasten/pull/407).
 Currently, the license detector consumes the SyncJava input topic, which should be updated to the [fasten.MetadataDBExtension.out](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenmetadatadbextension).
 
 I am not very confident about solving these conflicts. Sorry.
Can someone else look at them and eventually ask for my intervention?

**Pull request closed without merging**
