### PR TITLE
Optimizing the output of POMAnalyzer

### PR DESCRIPTION
**Pull request by mir-am**
## Description
The dependency data is removed from the output message of POMAnlyzer.

## Motivation and context
Currently, the output messages of POM Analyzer can be large due to the dependency information. However, this information is not used by downstream plug-ins via Kafka and also the dependencies data are stored in the metadata DB.

## Testing
We need to make sure that the upstream plug-ins will not break if the dependency info is absent for the output messages of POM Analyzer.

## Task list  
- [x] Removed the dependency data from the output JSON of POMAnalyzer

### CODE REVIEW

**Comment by mir-am** [comment]
@MagielBruntink @michelescarlato 
What is the verdict here?

**Comment by MagielBruntink** [comment]
LGTM, but we still need to hear from @michelescarlato

**Comment by michelescarlato** [comment]
> It makes sense to not include all those data in Kafka messages that has also been stored in a database table and as a JSON field.
> 
> @michelescarlato Do you plugins not use the POM Analyzer messages for further processing?

@marcomicera do our plugins use it?

**Comment by proksch** [comment]
@mir-am if this PR is still valid, please rebase it onto develop, so we fast-forward merge it into develop. If not, then please close it.

**Comment by mir-am** [comment]
I would like to close this PR since we have not heard back from the EC team. So I am not sure whether merging this PR will be 100% safe and without bad side effects for other partners.

**Comment by marcomicera** [comment]
I confirm that [`license-detector`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-detector) and [`license-feeder`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/license-feeder) do not consume `fasten.POMAnalyzer.out` records.

**Pull request closed without merging**
