### PR TITLE
Merging WALA plug-in branch

### PR DESCRIPTION
**Pull request by mir-am**
I have created a branch in the main repo of the project for WALA plug-in. Other members and Ilya can now contribute and commit to this PR. Discussion about merging this PR will be continued here.

For now, I did the followings:
- Merged this PR with the new commits in the master branch and resolved the conflicts.
- Fixed `setPlugingError` method for Wala plug-in and its tests.

I will further test the WALA plug-in in the FASTEN server and report the potential problems.

### CODE REVIEW

**Comment by mir-am** [comment]
@ilyagrishkov, @ashkboos 
I have tested WALA plug-in with `mvn.dataset` [here](https://github.com/fasten-project/fasten/tree/master/dataset). However, it doesn't generate call graphs for most of the Maven coordinates in the dataset. The plug-in throws `FileNotFoundException.`, even though the JAR file of those coordinates is available. 
Two failed records with exception and debug info are as follows:
```
{"date":"1546602120","groupId":"au.net.zeus.jgdms.outrigger","artifactId":"outrigger-dl","error":"{\"msg\":\"https://repo.maven.apache.org/maven2/au/net/zeus/jgdms/phoenix-activation/3.0.1-RC-07/phoenix-activation-3.0.1-RC-07.jar\",\"trace\":[\"java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)\",\"java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)\",\"java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)\",\"java.base/java.net.URL.openStream(URL.java:1139)\",\"eu.fasten.analyzer.javacgwala.data.MavenCoordinate$MavenResolver.httpGetToFile(MavenCoordinate.java:294)\",\"eu.fasten.analyzer.javacgwala.data.MavenCoordinate$MavenResolver.downloadJar(MavenCoordinate.java:260)\",\"eu.fasten.analyzer.javacgwala.data.callgraph.CallGraphConstructor.build(CallGraphConstructor.java:51)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.generateCallgraph(WALAPlugin.java:132)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.consume(WALAPlugin.java:93)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.consume(WALAPlugin.java:66)\",\"eu.fasten.server.kafka.FastenKafkaConsumer.run(FastenKafkaConsumer.java:300)\"],\"plugin\":\"WALA\",\"type\":\"FileNotFoundException\"}","version":"3.1.0","url":"https://repo1.maven.org/maven2/au/net/zeus/jgdms/outrigger/outrigger-dl/3.1.0/outrigger-dl-3.1.0.pom"}
```

```
{"date":"1545411600","groupId":"au.net.zeus.jgdms","artifactId":"service-starter","error":"{\"msg\":\"https://repo.maven.apache.org/maven2/au/net/zeus/jgdms/tools/3.0.1-RC-07/tools-3.0.1-RC-07.jar\",\"trace\":[\"java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)\",\"java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)\",\"java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)\",\"java.base/java.net.URL.openStream(URL.java:1139)\",\"eu.fasten.analyzer.javacgwala.data.MavenCoordinate$MavenResolver.httpGetToFile(MavenCoordinate.java:294)\",\"eu.fasten.analyzer.javacgwala.data.MavenCoordinate$MavenResolver.downloadJar(MavenCoordinate.java:260)\",\"eu.fasten.analyzer.javacgwala.data.callgraph.CallGraphConstructor.build(CallGraphConstructor.java:51)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.generateCallgraph(WALAPlugin.java:132)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.consume(WALAPlugin.java:93)\",\"eu.fasten.analyzer.javacgwala.WALAPlugin$WALA.consume(WALAPlugin.java:66)\",\"eu.fasten.server.kafka.FastenKafkaConsumer.run(FastenKafkaConsumer.java:300)\"],\"plugin\":\"WALA\",\"type\":\"FileNotFoundException\"}","version":"3.0.1-RC-07","url":"https://repo1.maven.org/maven2/au/net/zeus/jgdms/service-starter/3.0.1-RC-07/service-starter-3.0.1-RC-07.pom"}
```

I think that there is a problem with creating the URL of the JAR file of a Maven coordinate. We can run the two attached coordinates in the Main class of the plug-in and debug the issue.

**Comment by ilyagrishkov** [comment]
@mir-am Thank you for testing the plugin. I will address this issue and will try to come up with a solution. It's an interesting error though, as MavenCoordinate is almost identical to OPAL's one. I'll debug it.

**Comment by ilyagrishkov** [comment]
@mir-am I changed the way Wala plugin processes generated CG. The problem with two coordinates that you've mentioned (when run locally) was a NullPointerException on arrays of primitive types, because Wala couldn't process them properly. MavenCoordinate has never thrown a FileNotFoundException at least locally. So now both of coordinates are successfully passing when run in the Main class.

**Comment by mir-am** [comment]
> @mir-am I changed the way Wala plugin processes generated CG. The problem with two coordinates that you've mentioned (when run locally) was a NullPointerException on arrays of primitive types, because Wala couldn't process them properly. MavenCoordinate has never thrown a FileNotFoundException at least locally. So now both of coordinates are successfully passing when run in the Main class.

Thanks for working on the problem. Actually, the `FileNotFoundException` happened locally on my machine. Anyhow, I will test it again and let you all know about the results.

**Comment by mir-am** [comment]
@ilyagrishkov 
I have tested the WALA plug-in with the FASTEN server. It doesn't throw false `FileNotFoundException` anymore. However, the WALA plug-in now generates lots of empty call graphs. For instance, check out these two Maven coordinates:

```
au.net.zeus.jgdms:phoenix-activation:3.0.1-RC-07
```
```
au.net.zeus.jgdms.outrigger:outrigger-service:3.1.0
```
Both of the coordinates gives empty call graphs on the FASTEN server as well as the Main class of the plug-in.

Do you think that it might be related to the JRE version and its path? I set it to my local Java installation which is Java 11!

**Comment by ilyagrishkov** [comment]
@mir-am 
I tested it on my computer in the Main method. The first coordinate throws FileNotFoundException, but the second one works well. It is most likely because of the JRE problem. Wala requires a path to JRE 8 in wala.properties

**Comment by mir-am** [comment]
@ilyagrishkov 
Thanks for the contribution and improving the WALA module.
I managed to install JDK8 locally and generate a call graph using the Main class of WALA.

For now, please merge the master branch into your branch and fix the possible conflicts. I will help you with resolving the potential conflicts.
I would like to test the WALA plug-in with the latest version of the FASTEN server.

**Comment by ilyagrishkov** [comment]
@mir-am 
Merged. There was no conflicts as I had been working on Wala module only. Thank you for offering help though.

**Comment by mir-am** [comment]
@ilyagrishkov 
Please fix the build error by not attaching the JRE inside the JAR file. I would like to test the plug-in inside a Docker container.
Thanks.

**Comment by ilyagrishkov** [comment]
@gousiosg @mir-am @ashkboos 
Wala plugin is ready for the review and merging, so here are some final remarks: 

1. It has been refactored and now is fully compatible with the latest version of ExtendedRevisionCallGraph in the core;
2. Plugin has been tested on a dataset consisting of **120 Maven Coordinates** and here are the results: for 89 coordinates call graphs were generated [**success rate 74%**], 29 throw FileNotFoundException, 2 throw UnimplementedError from within Wala itself;
3. MavenCoordinate now creates **nested dependency sets for profiles** if they are present in the pom.xml;
4. All exceptions are being propagated until the plugin class where they are handled;
5. Main method can generate call graphs for both single coordinates as well as for datasets;
6. The coverage is **94% [statement]** and **91% [branch]**;
7. 0 Checkstyle & 0 PMD warnings.

**Pull request merged**
