### PR TITLE
License detection for C & Python

### PR DESCRIPTION
**Pull request by ddentale**
## Description
Extending the license detector plugin, currently working for Java/Maven projects, to detect licenses for Python and C projects too.

## Motivation and context
This change is required to fulfill the project requirements 

## Testing
To test the new added features some additional open source Python and C projects will be identified to be used in the license detection unit tests

## Task list  
- [ ] Extract some reusable code from the LicenseDetectorPlugin
- [ ] Create license detector classes specialized for Python and C projects
- [ ] Integrate the new code with the main LicenseDetectorPlugin class

### CODE REVIEW

**Comment by marcomicera** [comment]
@ddentale this should merge into [`endocode/compliancePlugin`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin).

**Comment by marcomicera** [comment]
I'll integrate this new outbound license detection method on [`endocode/compliancePlugin`](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin) after we have clear in mind how to make the `license-detector` plugin consume 3 different input topics.

I.e., the same `license-detector` plugin should consume records regarding C, Python, and Maven projects.
As of now, it consumes records belonging to the `fasten.SyncJava.out` topic, which combines `fasten.RepoCloner.out` and `fasten.MetadataDBJavaExtension.out`. The latter is Maven-specific, so that's a problem.

**Comment by proksch** [comment]
I am curious about the state of this PR. The server natively supports multi-topic subscriptions by now and the new loader platform even makes the whole discussion unnecessary, as the whole workflow got simplified.

Is there clarification needed for how to use it or how could we help? It would be great if the code would be updated to the current state of `develop` branch (preferably through a rebase ;)) then I could offer a helping hand to get the multi-topic subscriptions working.

Should this PR draft be obsolete by now, I would kindly ask to close it.

**Comment by michelescarlato** [comment]
Hi Sebastian @proksch, thanks for the notification.

IMHO, I don't think this PR will be helpful. I will use a completely different approach for Debian, and the Debian License Detector plugin will not share almost anything with the License Detector.

For Python, I think the multi-topic subscription still makes sense, but I will refactor/add missing functions and keep the code structure written by Marco.  

Said that, I would like to close it.

Thanks again.

**Pull request closed without merging**
