### PR TITLE
Increased Kafka max request size to 200 MB.

### PR DESCRIPTION
**Pull request by MagielBruntink**
This should allow big call graphs to be sent from metadata db extension to graph db extension (eg. fastutil).

### CODE REVIEW

**Comment by wzorgdrager** [comment]
This resolves the size issue on the client-side. If we want to resolve this completely, we need to set the same values in all the brokers (which requires a broker restart). As @proksch mentioned in #256, we can also write the payloads to disk. In that case, this PR is unnecessary. I will discuss internally if we can simply restart the metadata plugin with the correct flags to write to disk.

**Comment by MagielBruntink** [comment]
@wzorgdrager @proksch Did you reach a conclusion on this?

**Comment by proksch** [comment]
Sorry, this "internal discussion" has never been initiated. My personal preference would be to follow the example of the call graph generator and serialize the payload to disk.

**Comment by wzorgdrager** [comment]
I actually tried to redeploy it but there is a bug in the code (in short; it seems that there is no proper output path for the metadata plugin which can only be set in the code). I will try to resolve this bug the coming weekend, redeploy and let you know.

**Comment by wzorgdrager** [comment]
An update for now; I've refactored some of the code and redeployed the plugin, however for some reason it does not write to disk yet. It's odd because it does work for OPAL. We have to look into this.

**Comment by MagielBruntink** [comment]
@wzorgdrager There appears to be no code that actually writes the call graph to disk at all, just produce a json gidgraph to its output topic and done.

**Comment by proksch** [comment]
This change was never merged, is it still relevant? After the discussion that we had some days ago in the dev call, it seems that we decided to avoid large messages in the future (esp. the call graphs), so I would assume that we can reject and close this change?

**Comment by MagielBruntink** [comment]
You are right, this should be closed without a merge.

**Comment by amottier** [comment]
@MagielBruntink is it ok to delete [increase-max-kafka-request-size-to-200mb](https://github.com/fasten-project/fasten/tree/increase-max-kafka-request-size-to-200mb) branch?

**Comment by MagielBruntink** [comment]
Done

**Pull request closed without merging**
