### PR TITLE
Metadata Database Plugin

### PR DESCRIPTION
**Pull request by MihhailSokolov**
This plugin consumes Kafka topic and populates the metadata database.
(It is still work in progress)

### CODE REVIEW

**Comment by gousiosg** [comment]
Can you make the code more Java 11? For example, `Record record = new Record`  can be converted to `var record = new Record`

**Comment by gousiosg** [comment]
Also, in `MetadataDao.java`, you should have methods that insert multiple records and return multiple IDs, for example:
```java
public List<long> insertCallables(long fileId, List<String> fastenUri, Timestamp createdAt, List<JSONObject> metadata)
```

In pure JDBC, you would use a prepared statement to add those; please use the equivalent in JOOQ.

**Comment by MihhailSokolov** [comment]
> Can you make the code more Java 11? For example, `Record record = new Record` can be converted to `var record = new Record`

Done, thanks for the tip!

**Comment by MihhailSokolov** [comment]
> Also, in `MetadataDao.java`, you should have methods that insert multiple records and return multiple IDs, for example:
> 
> ```java
> public List<long> insertCallables(long fileId, List<String> fastenUri, Timestamp createdAt, List<JSONObject> metadata)
> ```
> 
> In pure JDBC, you would use a prepared statement to add those; please use the equivalent in JOOQ.

Internally  jOOQ almost always uses prepared statements. However, at the moment jOOQ doesn't provide a nice method that would allow to add multiple records and get their IDs. There is a method called `batchInsert()` which can insert multiple records, but it doesn't return the IDs of those records. Since we really do need those IDs, I've decided for now just call multiple times already implemented method to add one records.
jOOQ has an open issue to implement this kind of functionality, so it will probably come out at some point in the future. Then we can change these methods.

**Comment by mir-am** [comment]
Please continue the review and discussion here:
https://github.com/fasten-project/fasten/pull/11

**Pull request closed without merging**
