### PR TITLE
Fixes to make building and testing FASTEN succeed on Windows

### PR DESCRIPTION
**Pull request by MagielBruntink**
## Description
Several assumptions in code do not work on Windows. This PR attempts to fix those.

## Motivation and context
FASTEN claims to offer a development environment for Windows, Linux, and Mac.

### CODE REVIEW

**Comment by mir-am** [comment]
Thanks for the PR.
Should we also set up a Windows-based CI like AppVeyor?

**Comment by MagielBruntink** [comment]
All tests succeed on my local Windows 10 system.

**Comment by MagielBruntink** [comment]
What do you guys think, should we invest time into setting up a Windows CI pipeline as well?

**Comment by mir-am** [comment]
> What do you guys think, should we invest time into setting up a Windows CI pipeline as well?

If there are several Windows developers, we can also set up a Windows CI. However, speaking from our side, we develop on either Linux or macOS.

**Review by mir-am — APPROVED** [review]
Thanks for fixing the project build on Windows.
LGTM!

**Pull request merged**
