### PR TITLE
Sig/javacgopal cli merge

### PR DESCRIPTION
**Pull request by cg122**
## Description

JavaCGOpal does not write (raw and resolved) call graph of dependencies to JSON files. Only raw/resolved call graph of artifact write to the output file.

## Motivation and context

When running JavaCGOpal locally, it is preferable to write all call graphs into separate JSON files.

## Task list  

- [x] Write raw call graph of artifact and dependencies to different JSON files.
- [x] Resolve all the call graphs of provided dependencies.

## Additional context

The function changes the semantic of CLI option -o, the command to generate all raw/resolved call graphs of artifact and dependencies (from files and assuming all transitive dependencies included) as below:

-a path/to/artifact -d path/to/dependencies -s -ma CHA -o path/to/output

### CODE REVIEW

**Comment by mir-am** [comment]
@cg122 
Thanks for your contribution.
@ashkboos, I highly appreciate it if you could also review this PR and especially validating the correctness of the deps. merging.

**Review by ashkboos — APPROVED** [review]

**Review by ashkboos — APPROVED** [review]

**Comment by gousiosg** [comment]
What is the status of this PR?

**Review by ashkboos — APPROVED** [review]

**Review by ashkboos — COMMENTED** [review]
Are you using the doAll anywhere in the code? I couldn't find it

**Comment by cg122** [comment]
> Are you using the doAll CLI variable anywhere in the code? I couldn't find it

No, it is supposed to be used to not break functionality of any present options. Now we switched to [https://github.com/fasten-project/rapid-integration-tools](url) to do the local merge. We currently hold the development in JavaCGOPAL CLI.

**Comment by proksch** [comment]
Is this PR still relevant?

**Comment by cg122** [comment]
No, I plan to close this one.

**Comment by amottier** [comment]
@cg122 is it ok to delete [javacgopal-cli-merge](https://github.com/fasten-project/fasten/tree/sig/javacgopal-cli-merge) branch?

**Pull request closed without merging**
